# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: windows-latest

stages:
  - stage: java_build_stage
    displayName: "maven build"
    jobs:
      - job: Build_java
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'sampleWebApp/pom.xml'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(system.defaultworkingdirectory)'
            Contents: '**/*.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
          condition: succeededOrFailed()

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
          condition: succeededOrFailed()
        # - task: Maven@3
        #   inputs:
        #     mavenPomFile: 'sampleWebApp/pom.xml'
        #     goals: 'package'
        #     publishJUnitResults: true
        #     testResultsFiles: '**/surefire-reports/TEST-*.xml'
        #     javaHomeOption: 'JDKVersion'
        #     mavenVersionOption: 'Default'
        #     mavenAuthenticateFeed: false
        #     effectivePomSkip: false
        #     sonarQubeRunAnalysis: false
        # - task: CopyFiles@2
        #   inputs:
        #     SourceFolder: '$(system.defaultworkingdirectory)'
        #     Contents: '**/*.jar'
        #     TargetFolder: '$(build.artifactstagingdirectory)'
        #   condition: succeededOrFailed()
        # - task: PublishBuildArtifacts@1
        #   inputs:
        #     PathtoPublish: '$(build.artifactstagingdirectory)'
        #   condition: succeededOrFailed()
  - stage: create_bug_report
    displayName: "Create workitem"
    condition: in(dependencies.java_build_Stage.result, 'Succeeded' , 'failed')
    jobs:
      - job: Create_workitem
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'createbug.ps1'
            condition: succeededOrFailed()
  - stage: Deploy_web_app
    displayName: "Deploy"
    condition: in(dependencies.java_build_stage.result, 'succeeded' , 'failed')
    jobs:
      - job: Deploy_web_app
        steps: